### PR TITLE
Added and integrated gif of app in the Readme.md

### PR DESCRIPTION
**Pull request by sankalpchauhan-me**
The compressed gif is present inside assets folder and is integrated into Readme[dot]md, it shows the working of the app.
Added name to Contributors[dot]md as mentioned in the issue.
**Edit1: ** Will create a separate PR for updating Contributors[dot]md

### CODE REVIEW

**Comment by sankalpchauhan-me** [comment]
Issue #6

**Comment by arshadkazmi42** [comment]
@sankalpchauhan-me You should create seperate PR for different features.

Break this into two PR.
1. Contributors.md
2. Adding Gif

also avoid working on master branch. its bad practice to work on master branch.
create separate feature branch for each feature you are working on.

**Comment by arshadkazmi42** [comment]
That's correct you have to create feature branch from your fork branch

**Comment by arshadkazmi42** [comment]
This PR looks good. merging it now.

**Pull request merged**
